# Generated by Django 3.1.2 on 2020-11-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('vlanA', models.CharField(max_length=50)),
                ('vlanB', models.CharField(max_length=50)),
                ('vlanC', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='switchhost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('ipadd', models.CharField(max_length=50)),
                ('devicerole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='switchconfig.role')),
            ],
        ),
    ]
