# Generated by Django 3.1.2 on 2021-01-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('switchconfig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='vlanA',
        ),
        migrations.RemoveField(
            model_name='role',
            name='vlanB',
        ),
        migrations.RemoveField(
            model_name='role',
            name='vlanC',
        ),
    ]
